name: CD
on:
  push:
    branches: [master]
env:
  REPOSITORY: ${{ github.repository }}
  GHCR_URL: ghcr.io # GitHub Container Registry
  AWS_ECR_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Get version from pom.xml
        id: get-version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_URL }} # GitHub Container Registry
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}
      - name: Build Docker image
        run: docker build  -t $REPOSITORY:$VERSION .
      - name: Tag and Push on GitHub Packages
        run: |
          docker tag $REPOSITORY:$VERSION $GHCR_URL/$REPOSITORY:$VERSION
          docker tag $REPOSITORY:$VERSION $GHCR_URL/$REPOSITORY:latest
          docker push $GHCR_URL/$REPOSITORY:$VERSION
          docker push $GHCR_URL/$REPOSITORY:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login in AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag and Push AWS ECR
        run: |
          docker tag $REPOSITORY:$VERSION $AWS_ECR_URL/$REPOSITORY:latest
          docker push $AWS_ECR_URL/$REPOSITORY:latest