name: CI
on:
  push:
    branches: [develop]
jobs:
  devops:
    name: Test - Unit & Integration & SonarCloud Scan & Slack WebHook
    runs-on: ubuntu-22.04 # macos-latest macos-11 windows-2019 ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode

